### PR TITLE
Change stream type to support playing via earpiece

### PR DESCRIPTION
**Pull request by ghsdh3409**
* Change stream type to support playing via earpiece
* **This is a temporary fix! Thus, it will not be merged!**
* This issue will be handled officially in the https://github.com/hayanmind/mimiking-rn/issues/1203.

### CODE REVIEW

**Review by ohtangza — APPROVED** [review]
It seems that STREAM setting is very important.

**Comment by ghsdh3409** [comment]
@ohtangza Please change review state to change request! I don't want to merge this!

**Review by ohtangza — COMMENTED** [review]
For state change.

**Review by ohtangza — CHANGES_REQUESTED** [review]
.

**Comment by ghsdh3409** [comment]
I close this since #2 resolves this issue officially.

**Pull request closed without merging**
